"""initial schema

Revision ID: 00be55c40254
Revises: 
Create Date: 2025-08-30 03:52:46.606238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00be55c40254'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buoy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buoy_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_m_s', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('haze', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buoy_id'], ['buoy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_lon'), ['lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_observed_at'))
        batch_op.drop_index(batch_op.f('ix_observation_lon'))
        batch_op.drop_index(batch_op.f('ix_observation_lat'))

    op.drop_table('observation')
    op.drop_table('buoy')
    # ### end Alembic commands ###
